---
- name: Deploying Project with Apache
  hosts: all
  remote_user: olyungdev
  become: yes
  become_method: sudo

  tasks:
  - name: Install Apache 2 on Ubuntu
    apt:
      name: 
      - apache2
      - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_os_family == 'Debian' || ansible_distribution == 'Ubuntu'
  
  #- name: Start apache, if not started
  #  service:
  #    name: apache2
  #    state: started
  #  when: andible_distribution in ["Debian", "Ubuntu"]

  - name: Install Apache 2 on RedHat/CentOS
    dnf:
      name: 
      - httpd
      - php
      state: latest
      update_cache: yes
    when: ansible_os_family == 'RedHat' || ansible_distribution == 'CentOS'

  - name: Start apache, if not started
    service:
      name: httpd
      state: started
      enbaled: yes
    when: andible_distribution in ["RedHat", "CentOS"]

  - name: Enable port 80
    firewalld:
      zone: public
      port: 80/tcp
      state: enabled
      permanent: true

#  - name: Clone Project repo
#    git:
#      repo: # public repo of project here.
#      dest: /var/www/html/
#      clone: yes
#      update: yes

  - name: copy php file to document root
    copy:
      src: /vagrant_data/altschool/class-work/tic_tac_toe/*
      dest: /var/wwww/htmm/
      owner: $USER
      group: www-data
      mode: 0644
      
  - name: rename existing index.html
    command: mv /var/www/htm/index.html /var/www/html/index_old.html